import random

def tad(x):
  truths = ['What was the last thing you searched for on your phone?',
'If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?',
'Have you ever walked in on your parents doing it?',
'Whats the first thing you would do if you woke up one day as the opposite sex?',
'Have you ever peed in the pool?',
'Who do you think is the worst-dressed person in this room?',
'Have you ever farted in an elevator?',
'True or false: You have a crush on either of the player.'
'Of the people in this room, who do you want to trade lives with?',
'What are some things you think about when sitting on the toilet?',
'Did you have an imaginary friend growing up?',
'Do you cover your eyes during a scary part in a movie?',
'Have you ever practiced kissing in a mirror?',
'Did your parents ever give you the “birds and the bees” talk?',
'What is your guilty pleasure?',
'What is your worst habit?',
'Has anyone ever walked in on you when going #2 in the bathroom?',
'Have you ever had a wardrobe malfunction?',
'Have you ever walked into a wall?',
'Do you sing in the shower?',
'What was your most embarrassing moment in public?',
'Do you ever talk to yourself in the mirror?',
'What would be in your web history that you’d be embarrassed if someone saw?',
'Have you ever tried to take a sexy picture of yourself?',
'Do you sleep with a stuffed animal?',
'Do you drool in your sleep?',
'Do you talk in your sleep?',
'Who is your secret crush?',
'Do you think your ex is cute?',
'Who do you like the least in this room, and why?',
'What does your dream boy or girl look like?',
'What is your go-to song for the shower?',
'Who is the sexiest person in this room?',
'Would you rather have sex with (the players decide the name) in secret or not have sex with that person, but everyone thinks you did?',
'What was the last thing you texted to a person personally?',
'If you were rescuing people from a burning building and you had to leave one person behind from this room, who would it be?',
'Do you think youll marry your current girlfriend/boyfriend?',
'What is the most illegal thing you have ever done?',
'Would you trade your sibling in for a million dollars?',
'Would you trade in your dog for a million dollars?',
'What is your biggest pet peeve?',
'If you were allowed to marry more than one person, would you? Who would you choose to marry?',
'Would you rather lose your sex organs forever or gain 200 pounds?',
'Would you choose to save 100 people without anyone knowing about it or not save them but have everyone praise you for it?',
'If you lost one day of your life every time you said a swear word, would you try not to do it?',
'Who in this room would be the worst person to date? Why?',
'Would you rather live with no internet or no A/C or heating?',
'If someone offered you $1 million to break up with your girlfriend/boyfriend, would you do it?',
'If you were reborn, what decade would you want to be born in?',
'If you could go back in time in erase one thing you said or did, what would it be?',
'Has your boyfriend or girlfriend ever embarrassed you?',
'Have you ever thought about cheating on your partner?',
'Have you ever been caught checking someone out?',
'Have you ever waved at someone thinking they saw you when really they didnt? What did you do when you realized it?',
'Whats the longest time youve stayed in the bathroom, and why did you stay for that long?',
'Whats the most unflattering school picture of you?',
'Have you ever cried because you missed your parents so much?',
'Describe the strangest dream youve ever had. Did you like it?',
'Have you ever posted something on social media that you regret?',
'What is your biggest fear?',
'Have you ever ding dong ditched someone?',
'The world ends next week, and you can do anything you want (even if its illegal). What would you do?',
'Would you wear your shirt inside out for a whole day if someone paid you $100?',
'What is the most childish thing that you still do?',
'How far would you go to land the guy or girl of your dreams?',
'Tell us about a time you embarrassed yourself in front of a crush.',
'Have you ever kept a library book?',
'Who is one person you pretend to like, but actually don’t?',
'What children’s movie could you watch over and over again?',
'Do you have any silly nicknames?',
'If you had to make out with any Disney character, who would it be?',
'Have you ever watched a movie you knew you shouldn’t?',
'Have you ever wanted to try LARP (Live Action Role-Play)?',
'What app on your phone do you waste the most time on?'
'What is the most food you’ve eaten in a single sitting?',
'Do you dance when you’re by yourself?',
'What song on the radio do you sing with every time it comes on?',
'Do you own a pair of footie pajamas?',
'Are you scared of the dark?',
'What "as seen on TV" product do you secretly want to buy?',
'If you were home by yourself all day, what would you do?',
'What is something you’ve done to try to be ‘cooler’?',
'Do you have a security blanket?',
'Have you ever eaten something off the floor?',
'Have you ever butt-dialed someone?',
'Do you like hanging out with your parents?',
'Have you ever got caught doing something you shouldn’t?',
'What part of your body do you love, and which part do you hate?','classify each player as whom would you marry,kiss or have sex with',
'Have you ever had lice?',
'Have you ever pooped your pants?',
'What was the last R-rated movie you watched?',
'Do you lick your plate?',
'What is something that no one else knows about you?',
'Do you write in a diary?'

        ]
  dares = [
            'Make a call to your teacher. Ask, when will be the surprise test?',
            'That one thing that scares you the most.',
            'Behave like a Chinese for the next 5-10 minutes.',
            'Call your older family members and ask about weekend plans.',
            'Keep jumping until your next turn. ',
            'Describe what’s your dream job like. ',
            'Mimic your favorite celebrity.',
            'Predict the future of every person in this room. ',
            'Sing like you are a mouse with a high tone. ',
            'Pretend like you are a scooter for five minutes. ',
            'Go into silent mode, till your next turn.',
            'Name a person you have to show you like, But hate for no reason.',
            '1-10, rate yourself, How confident do you feel about yourself?',
            'Show us how many dating apps you’ve installed.',
            'Grab your personal diary and read it aloud here.',
            'Share something that you are hiding from your parents.',
            'Cut four onion and show us you can cry, too.',
            'Open a job portal and send applications to any random jobs.',
            'Locked yourself in the bathroom till your next turn.',
            'Call someone randomly and say, You have a crush on them.',
            'Share your mobile lock screen password.',
            'Behave like you are Michael Jackson for the next 10 minutes.',
            'Take an embarrassing selfie and post it as your profile picture.',
            'Remove your socks with your teeth.',
            'Go next door with a measuring cup and ask for a cup of sugar.',
            'Let the group choose an item for you to brush your teeth with.',
            'Write your name on the floor with your tongue.',
            'Stick a Hot Cheeto in your nose, and leave it there for five minutes.',
            'Open your front door and howl like a wolf for 30 seconds.',
            'Let the person to your right put duct tape on any part of your body they choose and rip it off.',
            'Put a bunch of honey on your nose and coat it with flour.'
        ]
  if (x==1):
    return random.choice(truths)
  elif (x==2):
    return random.choice(dares)